<#
.SYNOPSIS
Builds the Godot addon zip (addons/game_lattice) for a given version.

.DESCRIPTION
Compiles packaging/bundle/Lattice.Bundle.csproj to collect the full Lattice
dependency closure, stages the addon layout (DLLs under bin/, a generated
GameLattice.props that references them, README, LICENSE, VERSION), and emits:

  <OutputDir>/game-lattice-addon-<Version>.zip

The zip has a top-level addons/ folder, the layout the Godot editor and Asset
Store importer expect. Runs on Windows PowerShell 7+ and pwsh on Linux CI.

.EXAMPLE
pwsh scripts/Build-GodotAddon.ps1 -Version 0.1.1
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^\d+\.\d+\.\d+(-[0-9A-Za-z\.-]+)?$')]
    [string]$Version,

    [string]$OutputDir
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
if (-not $OutputDir) { $OutputDir = Join-Path $repoRoot 'artifacts' }

Write-Host "Building dependency closure..."
dotnet build (Join-Path $repoRoot 'packaging/bundle/Lattice.Bundle.csproj') -c Release
if ($LASTEXITCODE -ne 0) { throw "dotnet build failed" }

$binSrc = Join-Path $repoRoot 'packaging/bundle/bin/Release/netstandard2.1'
$staging = Join-Path $OutputDir 'godot-staging'
$addonDir = Join-Path $staging 'addons/game_lattice'
if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
$binDir = New-Item -ItemType Directory -Force (Join-Path $addonDir 'bin')

Copy-Item (Join-Path $repoRoot 'packaging/godot/README.md') $addonDir
Copy-Item (Join-Path $repoRoot 'LICENSE') (Join-Path $addonDir 'LICENSE.md')
Set-Content -Path (Join-Path $addonDir 'VERSION') -Value $Version

$dlls = Get-ChildItem $binSrc -File |
    Where-Object { $_.Name -notlike 'Lattice.Bundle.*' -and $_.Extension -in '.dll', '.pdb' } |
    Sort-Object Name
$dlls | Copy-Item -Destination $binDir

# GameLattice.props: users <Import> this from their Godot .csproj to reference
# every bundled assembly without hand-writing HintPaths.
$references = ($dlls | Where-Object Extension -eq '.dll' | ForEach-Object {
        $name = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
        "    <Reference Include=`"$name`">`n      <HintPath>`$(MSBuildThisFileDirectory)bin/$($_.Name)</HintPath>`n      <Private>true</Private>`n    </Reference>"
    }) -join "`n"

Set-Content -Path (Join-Path $addonDir 'GameLattice.props') -Value @"
<Project>

  <!-- Game Lattice $Version - generated by scripts/Build-GodotAddon.ps1.
       Import from your Godot project's .csproj:
       <Import Project="addons/game_lattice/GameLattice.props" /> -->
  <ItemGroup>
$references
  </ItemGroup>

</Project>
"@

New-Item -ItemType Directory -Force $OutputDir | Out-Null
$zip = Join-Path $OutputDir "game-lattice-addon-$Version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($staging, $zip)

Write-Host "Godot addon zip: $zip"
